### ISSUE TITLE
Possible bug in allocate_petsc_csr_matrix_from_nnz with blocks

### ISSUE THREAD

**Issue by stevendargaville** [FluidityProject/fluidity#122]
The method allocate_petsc_csr_matrix_from_nnz in Sparse_Tools_Petsc.F90 seems broken when trying to build a block matrix, namely the petsc numbering is created too large and so a debugging assert fails.

If _element_size_ is present, on Line 317 the _index_rows_ (and the _index_columns_) is set to be the _rows_ * _element_size_, where the input _rows_ is the number of element block rows, making _index_rows_ the actual number of rows in the matrix. 

When the _row_numbering_ is then created on Line 326, it is given _nnodes=index_rows,_ rather than the original number of element block rows. As such, the _row_numbering_ is created as size _index_rows * blocks(1)_, which is too large (namely it becomes the number of actual rows in the matrix * the block size). This then breaks in an assert on Line 364.

I think the fix for this would be to set the _index_rows_ and _index_cols_ to be of size _rows_ and _columns_. I think all the variables after this are then consistent (and consistent with the comments at the start of the routine).

This works for me, but I'm just a little worried that I have accidentally misunderstood the roles of _blocks_ and _element_size_ in this routine. @jrper suggested you might know more about this routine @stephankramer?

**Comment by stevendargaville** [comment]
Hmm so it seems like I had misunderstood the role of _blocks_ , what I actually wanted to do was set the _blocks_=(1,1) and use the element_size to set my block structure in my matrix.

**Comment by stephankramer** [comment]
I agree that this interface is very confusing. *blocks* are indeed something different then you might expect - they refer to the fact that in the *femtools* interface the DOFs can be numbered using a pair (i,b) with i<=N (typically a node number), and b<=B (typically the components of a vector field). The way these are stored in the matrix is: 1...N, N+1...2*N, ...., (N-1)*B+1...N*B (i.e. the blocks are on the "outside", b is the major numbering). If element_size is provided this divides the N numbering: N=E*element_size, where E (the "element numbering") is major with little blocks of 1..element_size within and this is handed over to PETSc to switch over to a MatBAIJ matrix format. This division of the N numbering does not change the numbering of DOFs in the femtools interface.

I actually think that for the rows and columns arguments of this routine it would be more consistent for them to represent N (rather than E) - because N is indeed the bound on the numbering seen from the femtools interface, and element_size is just some extra information to allow for storing in MatBAIJ format.

Note that if you want the element_size blocks to also change the numbering seen in the femtools/ interface we should discuss merging the fluidity-block-velocity branch which provides this functionality, i.e. you can then have a numbering (i,j) with 1<=i<=E and 1<=j<=element_size in your calls to set(), addto() etc - rather than a contiguous numbering 1...E*N - at the same time as using this as the MatBAIJ structure.

**Comment by stevendargaville** [comment]
Ok thanks for the clarification. I'm actually happy with the functionality as is, but I might also have a look at the fluidity-block-velocity branch.
