### ISSUE TITLE
C++ MPI bindings

### ISSUE THREAD

**Issue by alistaireverett** [FluidityProject/fluidity#175]
Hi all,

Apologies if this is something which you are aware of, or have already discussed. I'm trying to compile Fluidity on a new Norwegian HPC system (https://www.sigma2.no/Fram). Currently, they only provide OpenMPI >2.x and I've run into problems which appear to be related to OpenMPI dropping support for C++ MPI bindings (https://github.com/open-mpi/ompi/issues/3173#issuecomment-286738170). As a first step I've asked if they can recompile with the --enable-mpi-cxx, but there seems to be a little resistance to this (and for >3.x this isn't an option). I'll see if I can work towards a solution with them (and I'm happy to hear if anyone has any suggestions) but I thought it might be worth highlighting this as it may become more of an issue in future as newer HPC systems drop support for older OpenMPI versions.

One of the options I considered was switching the C++ MPI bindings to C. Playing with MPI bindings is a little outside my area of experience, but does anyone have a feeling for whether this might be a straightforward task or whether there would be any negative implications? If it's reasonably straightforward, I'd be happy to try and make these changes and see if I can get it going on the system here.

Thanks,
Alistair

**Comment by jrper** [comment]
Hello Alistair,

As far as I'm aware, nothing in the Fluidity C++ codebase is actually using anything specifically C++ flavoured, with all the underlying data types being C primitive types, just possibly wrapped through macros, so all or almost all of the changes would be search and replace style changes from things like `MPI::Init(argc, argv);` to `MPI_Init(&argc, &argv);`, from `NProcs = MPI::COMM_WORLD.Get_size();` to `MPI_COMM_size(MPI_COMM_WORLD, &size);` and so on.  Running `rep -r --include=*.cpp --exclude=*/CMakeFiles/* "MPI::" . | wc` suggests that this is about 235 lines of code. 

In theory this shouldn't hugely affect anything, since as I understand it, the C++ bindings are typically inlined wrappers around the underlying C code anyway.

**Comment by tmbgreaves** [comment]
This would be a very welcome migration from my end - I'm in the latter stages of building packages for Ubuntu 18.04 LTS which has MPI2 by default, hence we're going to hit this problem on our core testing platform in the next couple of months.

**Comment by alistaireverett** [comment]
Ok great, in that case I'll have a crack at creating a new branch and switching out the C++ bindings for C. I'll let you know how I get on!

**Comment by jrper** [comment]
Closed by #196.
