### ISSUE TITLE
How to static link with Zoltan

### ISSUE THREAD

**Issue by adamcavendish** [FluidityProject/fluidity#185]
fluidity does not seem to provide build configurations to link zoltan statically.
It uses `-lzoltan`  to link to only the dynamic library of zoltan.

Is it possible to link with zoltan statically?

The default zoltan build seems to build static library only.

**Comment by jrper** [comment]
Hi. Generically when passed a library as -lname, linkers will go through its default search order and link against the first matching library it finds. There may be options available to force one or the other, e.g. `-Wl,-Bstatic` and `-Wl,-Bdynamic` for when compilers call gnu `ld` linker. See e.g. https://stackoverflow.com/questions/6578484/telling-gcc-directly-to-link-a-library-statically for a usage pattern, and a couple of alternative solutions.

Unfortunately at the moment to implement any of these, you would have to go in and modify the root Makefile as well as the ones for the tools, since as you say the default build, as well as the AMCG packages only build the static version.

**Comment by adamcavendish** [comment]
Thx. Though a bit off topic, could youbtell me how you build zoltan as dynamic library?

**Comment by guoxiaohu** [comment]
I would recommend you build zoltan together with petsc using option 
'--download-zoltan',
you may need other option to meet up with dependencies.  And for the petsc version older than 3.8, you also need apply this patch for /petsc-*/config/BuildSystem/config/packages/Zoltan.py 

44a45,46
>     if hasattr(self.compilers, 'FC'):
>       args.append('--enable-f90interface')

**Comment by adamcavendish** [comment]
Hi, to those who configure fluidity with zoltan not found, the underlying secret is revealed as zoltan must be installed in PETSc's install directory, but not separately, which in other words, zoltan headers and `libzoltan.a` should live in the `$PETSC_HOME/include/` and `$PETSC_HOME/lib/` correspondingly.
