### ISSUE TITLE
Configure ok but make error (cannot find libmpi_usempif08.so)

### ISSUE THREAD

**Issue by tyszwh** [FluidityProject/fluidity#265]
**I have no idea on this error. This files exists, ldd command works fine, and the LD_LIBARAY_PATH include the path of file.I have attached the configure.log and make.log files fro detail message.**

```
libtool: link: mpif90 -shared  -fPIC  .libs/spud.o .libs/spud_interfaces.o .libs/tinystr.o .libs/tinyxml.o .libs/tinyxmlerror.o .libs/tinyxmlparser.o .libs/fspud.o  ..............................................
/usr/bin/ld: cannot find -l/home/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.2.0/openmpi-3.1.5-dfs5v4gmrfynpynzqbk3iloikq4rs7rq/lib/libmpi_usempif08.so
collect2: error: ld returned 1 exit status
Makefile:57: recipe for target 'libspud.la' failed
make[1]: *** [libspud.la] Error 1
Makefile:147: recipe for target '/home/3_10/CFD/fluidity/lib/libspud.a' failed
make: *** [/home/3_10/CFD/fluidity/lib/libspud.a] Error 2
```

[config.log.txt](https://github.com/FluidityProject/fluidity/files/4491235/config.log.txt)
[log.make.txt](https://github.com/FluidityProject/fluidity/files/4491237/log.make.txt)

**Comment by GNikit** [comment]
Hi thanks for the issue, I am just curious is there a reason why you are configuring with ` --prefix=/home/build_install/seperate/fluidity PYTHON_VERSION=3.7 --enable-shared --enable-python` have you tried doing a bog-standard configure with just `--enabled-2d-adaptivity`. 

Also, from what I could tell you albeit using a supported Ubuntu version you are not installing/loading the packages from the ppa which could certainly be an issue.
could you have a try using the fluidity ppa?

``` Bash
sudo add-apt-repository ppa:fluidity-core/ppa
sudo apt-get update
sudo apt install fluidity-dev-python3
```

**Comment by tyszwh** [comment]
A bog-standard configure with just --enabled-2d-adaptivity has the same error.
I just want to use the configure to set the install path and python3 version (I use this command for compiling the code last year(successful), I cannot remember the reason. Maybe  the  default python version is 2 in last year )

Yes, I have not tried to install fluidity from PPA Because I always compiled the code from a source to better manage the dependence. I have compiled it successfully in the last year with mpich and same command. Now I change the system variable such as open-mpi, petsc 3.12.4 and etc with spack. So I want to recompile current version.
It  seems to be related to the configure file of libspud from the log.make?

`libtool: link: mpif90 -shared  -fPIC  ......................................
-L/opt/moose/gcc-9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../.. 

**-l /home/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-9.2.0/openmpi-3.1.5-dfs5v4gmrfynpynzqbk3iloikq4rs7rq/lib/libmpi_usempif08.so** 

-L/opt/moose/gcc-9.2.0/lib/../lib64 
.................................`

I will try the PPA later.

**Comment by GNikit** [comment]
So a lot of things have changed over the past couple of years. The Fluidity devs made a big effort to "force" Python3 see (https://github.com/FluidityProject/fluidity/pull/238)  as the default one during the configure. So as far as I know, there is no need to explicitly specify any Python options since it will pick up the python3 that is in your path.

As for the second comment, the ppa is regularly update, but more importantly it is the how the CI (Jenkins) is configured and fluidity is tested locally and remotely.
Another thing to worry about is that the dependencies list has grown to include H5hut https://github.com/FluidityProject/fluidity/pull/230. 
I am not sure how you installed these dependencies, but the robust way is to do it through PETSc since then it is guaranteed that the libs work (directly obtained from the PETSc page). 

> - This will install the COMPATIBLE version of the external package. A generic install of this package might not be compatible with PETSc [perhaps due to version differences - or perhaps due to the requirement of additional patches for it to work with PETSc]
> - Some packages have bug fixes, portability patches, and upgrades for dependent packages that have not yet been included in an upstream release.
> - All packages will be installed with the same set of compilers - this avoids problems [for example weird link time errors] with mixing code compiled with multiple compilers [for example mixing gfortran and ifort compiled code].

Having said that, it appears that you don't have VTK in your system either: 

```
g++: error: VTK: No such file or directory
g++: error: not: No such file or directory
g++: error: found.: No such file or directory
g++: error: VTK: No such file or directory
g++: error: not: No such file or directory
g++: error: found.: No such file or directory
```
I am not sure if you can have fluidity without VTK since all of its I/O uses VTK.

Moreover, you seem to be getting a lot of these in your config.log 
`/usr/bin/ld: warning: libgfortran.so.4, needed by /home/build_install/seperate/fluidity/lib/liblapack.so, may conflict with libgfortran.so.5`

So as you can see there are a lot of dependencies that need to be taken care off if you want to build everything from source, hence my original comment about using the PPA.

**Comment by tyszwh** [comment]
Thanks for your reply,Dr GNikit.

**I compile PETSc with the below command.** expect the MPICH and HDF5 are built separately.
```
./configure --prefix=$BUILD_SEP/petsc3_12_5 \
--download-fblaslapack --download-blacs --download-scalapack \
--download-ptscotch --download-mumps --download-hypre \
--download-ml --with-fortran-interfaces --with-debugging=no \
--download-ctetgen --download-parmetis \
--download-suitesparse --download-eigen \
--download-f2cblaslapac --download-openblas \
--download-metis --download-superlu --download-trilinos --enable-shared=1
```
_I use the exist VTK and lapack compiled before. I do not know why Vtk automagic not work. But it should have find the include files and libraries.
Now I recompiled the dependencies, and solve these conflict. But the problem is still there_. 

```
/usr/bin/ld: cannot find -l/opt/moose/mpich-3.3/gcc-9.2.0/lib/libmpifort.so
collect2: error: ld returned 1 exit status
Makefile:57: recipe for target 'libspud.la' failed
make[1]: *** [libspud.la] Error 1
Makefile:147: recipe for target '/home/3_10/CFD/fluidity/lib/libspud.a' failed
```
Why there have a `-l` in front of  `-l/opt/moose/mpich-3.3/gcc-9.2.0/lib/libmpifort.so`? The lowcase L should not be work in here to find .so library. Where is it from?

**Comment by tyszwh** [comment]
The problem is solved. It just needs to add the rpath= in makefile.in of libspud for me. However, I do not know why there have a -l without "=".
