### ISSUE TITLE
fluidity does not work correctly with new metis/parmetis versions

### ISSUE THREAD

**Issue by stephankramer** [FluidityProject/fluidity#49]
There have been interface changes between parmetis 3.1 + metis 4, which fluidity uses and parmetis 4 + metis 5(.1) which have been out for quite a while now. Debian and Ubuntu packages are still on the older versions (although there is a libparmetis4 in experimental now). The reason this is an issue for a number of people is that petsc uses the new parmetis and metis versions, and if you build petsc with parmetis support fluidity picks up these instead of the older ones. Parmetis support for PETSc is necessary to use MUMPS (scotch support with MUMPS is broken).

Places we use metis/parmetis in fluidity:
* fldecomp calls metis and these calls need updating. We have discussed deprecating fldecomp previously - but some people (me a.o.) have indicated that they do some times still use it. Maybe it's time to revisit this discussion
* sam call parmetis. Again here the question is do we need maintain sam support or can everything been done via zoltan?

**Comment by drhodrid** [comment]
Thanks for bringing this up Steph. As I'm one of the people suffering because of these version conflicts I felt the need to respond!  So:

1. What do you (and others) still use fldecomp for? What functionality is not available through flredecomp? I personally only use flredecomp, so would not have a problem with fldecomp being thrown out (particularly since it would mean that we would no longer need to update our API's whenever there is an update to metis). All parallel tests (excluding fldecomp and fldecomp_2d) currently use flredecomp, so I can't see it being a big loss. 

2. I am of the opinion that everything can be done through zoltan. The original zoltan-tweeks branch did use some sam functionality, but the more robust version of this branch (strip-l2-halo) no longer does. I would therefore recommend dropping sam (although if people do have a  use for it, that should be highlighted here). 

If both of these are dropped, a large chunk of our external library dependencies could be grabbed through petsc (note I'm currently trying to get petsc to upgrade their interface to zoltan 3.81), which I think would be neater - and would leave to far less conflicts in the long term.

**Comment by ggorman** [comment]
The only real advantage of fldecomp is that it was optimised for memory usage so it could partition very large meshes. However, I think I was the only user of it in that respect and one could just as easily use a machine with more RAM. So - I don't see any problem with removing it.

If strip-l2-halo has been reimplemented without libsam then it would indeed be great to drop libsam. Having less code to maintain is a good thing.

**Comment by slmouradian** [comment]
The tsunami project currently used fldecomp. We can partition a mesh in seconds, at times, where flredecomp will take hours. These times are excluding time spent queuing.

**Comment by ggorman** [comment]
Ok - that sounds crazy. Why would it take hours? Can you put it through vtune to determine why it's so slow?

**Comment by stevendargaville** [comment]
The nuclear group still uses fldecomp, largely because we have our own schema type (which flredecomp complains about).

**Comment by jrper** [comment]
For those that haven't seen it, the conversation the last time this came up is documented at https://bugs.launchpad.net/fluidity/+bug/1040771

**Comment by ggorman** [comment]
@stevendargaville with regards to the nuclear fork - I think that should be considered a bug and flredecomp patched. Are you happy to take a closer look at that particular issue?

**Comment by jrper** [comment]
Not sure if it's any help, but I did look at it a while ago for the Darcy code. For codes which still use material_phases and Populate_State  calls, (i.e. codes where renaming the options file to .flml is enough to get flredecomp to run) then it's a fairly dull but trivial exercise to use Fortran string commands to build the proper filenames to get things working. I think the hard part was preserving the current behaviour as the default.

**Comment by drhodrid** [comment]
Ok - so it looks like there is:

1. A need to maintain support for fldecomp, thus requiring an update of the API.
2. No objection to dropping sam.

How should we proceed? Any volunteers for either? ;-)

**Comment by ggorman** [comment]
@drhodrid - not sure if I agree with 1. It boils down to work to update API and maintain an explicit METIS/PARMETIS dependency (as opposed to dependency via petsc and zoltan) Vs the Darcy branch being patched as @jrper points out. 

Therefore, I am advocating removing both the explicit permits/metis decency as well as purging sam. This is also consistent with the longer term plan of flipping to DMPlex.

The performance issue pointed out by @slmouradian is a straight up performance issue that requires someone to crack out vTune and fix it. I wild guess is that optimisations that I added to fldecomp could be reimplemented for flredecomp (they were not particularly difficult). Alternatively - we take the hit and focus on landing DMPlex as that will allow us to also purge flredecomp.

As for a volunteer...I have someone in mind ;-) But lets get agreement on the above first.

**Comment by jhill1** [comment]
Not sure I agree with @ggorman here. I doubt the performance issues will be easy to fix as it might lie within Zoltan (a general library) rather than our code. How long before DMPlex hits? If it's < 12 months, then it's probably fine to purge fldecomp and sam (not least as I could compile a static version of fldecomp to use :p).

Having said that, I'm not volunteering to maintain fldecomp myself and flredecomp dies do the job, albeit awkwardly.

**Comment by stevendargaville** [comment]
So I'm happy to look at flredecomp in terms of simply partitioning a mesh (without checkpointing) with an arbritrary schema. Like @jrper, I looked at it briefly a while ago and decided against doing it, because I don't think I understand enough about the actual re-partitioning part of flredecomp.

I migth come have a chat with you, @jrper about it.

**Comment by stephankramer** [comment]
Just to clarify @slmouradian's timing: I think he's talking about running a many core (100s) flredecomp on your desktop. I do that myself sometimes, do a `mpirun -n 256 flredecomp` on my 8 core desktop. This obviously utterly kills your machine and gives terrible performance. In principle you should just add the flredecomp in the same pbs script that you submit the fluidity run with. flredecomp simply runs the same initialisation that is run in fluidity before the first timestep - so there should never be any problem of it being impractily slow, as that would mean your fluidity run has the same delay when starting up.

Another suggestion could be that we make it a configure option whether to build fldecomp, and leave it out by default (just like same is). This means we could drop the direct metis/parmetis requirement for the default fluidity build and only if you configure --enable-fldecomp or --enable-sam would you need the specific *old* versions of metis and parmetis. If anyone still needs that functionality when these old version really start disappearing (say the Ubuntu and Debian packages are upgraded), they can decide if they want to do the legwork to upgrade it then.

**Comment by jrper** [comment]
@stevendargaville I've just pushed a branch (207ed7c3fed36712182d924c53fef71632440300) which pulls together my changes on the file naming front. providing adaptivity and checkpointing work for your code it might do what you want (unfortunately checkpointing is necessary to actually handle dumping all the output.

**Comment by drhodrid** [comment]
@stephankramer - to me that sounds like a very nice suggestion...

**Comment by jhill1** [comment]
@stephankramer fine with me too

**Comment by jrper** [comment]
Would it be acceptable to choose which version of Metis to include based on the version of parmetis found at configure time? After spending a bit of time on this, I think that could be done robustly. I'll try and pull the changes together into a branch and propose a merge request if @stephankramer is then willing to test it in an environment which isn't my mac.

On a related note, I'm suspicious that sam may now be broken, or at least when I accidentally build without zoltan on Darwin/OSX I had a raft of test failures.

**Comment by drhodrid** [comment]
Hi James,

I can test this on my local system as I have quite a few versions of metis and parmetis lying around... 

R

**Comment by jrper** [comment]
@drhodri ok, #51 has your name on it. If anyone else wants to improve my extremely limited autoconf macro, then feel free.
